### ISSUE TITLE
ダークテーマ対応

### ISSUE THREAD

**Issue by ryokohbato** [comfortable-panda/ComfortablePandATS#107]
## なぜ
PandAでは公式でダークテーマに対応していますが、これを有効化すると ComfortablePandATS の一部のテキストの色が見えにくくなります。

![image](https://user-images.githubusercontent.com/67552983/162972621-cff30fbd-e3b0-4658-bffc-ff7854eeb558.png)

## 解決策
解決策として、
1. 文字の色をライトテーマと同じになるようにする
2. ダークテーマに対応する

が考えられますが、PandAに合わせてダークテーマに対応してほしいという気持ちもあります。

**Comment by das08** [comment]
対応します！

**Comment by das08** [comment]
## その他修正点
- 色分けしたタブの講義名も見にくいので修正する
<img width="203" alt="minikui" src="https://user-images.githubusercontent.com/41512077/162982939-6fc4869d-4afb-439e-9b26-abb223f9828d.png">

**Comment by das08** [comment]
ダークモードに対応したv4.2.0を公開しました！
改善点があれば引き続きIssueなどで教えていただけるとありがたいです 🙇
