### ISSUE TITLE
miniPandAの講義名のリンクがおかしい

### ISSUE THREAD

**Issue by das08** [comfortable-panda/ComfortablePandATS#131]
`https://panda.ecs.kyoto-u.ac.jp/2022-110-xxxx-xxx`に飛んでしまう

**Comment by spinachpasta** [comment]
再現方法:

1. PandAからログアウト（右上の自分の氏名をクリックするとプルダウンが出てくる）
2. タブを閉じる
3. https://panda.ecs.kyoto-u.ac.jp/　にアクセス
4. ログイン
5. mini PandAの通知欄の科目ボタンを押す
6. https://panda.ecs.kyoto-u.ac.jp/202x-xxx-xxxx-xxx に飛んでしまう

**Comment by spinachpasta** [comment]
想定される正しい挙動
[https://panda.ecs.kyoto-u.ac.jp/portal/site/202x-xxx-xxxx-xxx](https://panda.ecs.kyoto-u.ac.jp/portal/site/202x-xxx-xxxx-xxx)

**Comment by das08** [comment]
Fixed this bug in commit [4d3df99](https://github.com/comfortable-panda/ComfortablePandATS/commit/4d3df9967b78cbe93cd8c548b35aa49ac401bb44).
