### ISSUE TITLE
課題提出時に自動的にチェックを付ける

### ISSUE THREAD

**Issue by das08** [comfortable-panda/ComfortablePandATS#60]
- [x] 課題提出の検出
- [ ] クイズ提出の検出
- [ ] 設定で「自動でチェックを付ける」がONのとき実行（デフォルトはOFF）

**Comment by tinaxd** [comment]
課題検出はほぼ完成（課題提出の瞬間じゃなくて、一歩手前で反応してしまう）

**Comment by das08** [comment]
https://github.com/comfortable-panda/ComfortablePandATS/pull/189
別のPRでマージしたのでクローズします
